### ISSUE TITLE
Need updating RPM files

### ISSUE THREAD

**Issue by jiro4989** [unkontributors/super_unko#29]
DockerのCentOSイメージで`yum`でインストールしたところ
unko.think, unko.say, unko.toilet, unko.shoutが動きませんでした。
おそらく外部コマンド依存系の新規に追加されたコマンド類のメンテ漏れかと思います。

yumのほうしか確認していませんが、もしかしたらdebファイルのほうでも同じ状態かもしれません。

**Comment by greymd** [comment]
遅くなりました。rpmファイルを更新しておきました！
