### ISSUE TITLE
TravisCIにosx環境のテストを追加する

### ISSUE THREAD

**Issue by jiro4989** [unkontributors/super_unko#45]
LinuxとMacでコマンドの挙動が違うのでテストしておきたい

**Comment by greymd** [comment]
いいですねー。一旦試してみるのはアリかもしれません。
ただ、今はどうかわからないんですが、TravisCIだとosxの起動がひどく重かった記憶が（タスクが開始されるまで1時間以上がかかったり）。bash観点の互換はLinuxで検証できているということで、デフォルトのシェルのバージョンだけで走らせるのはありかなーと。

**Comment by jiro4989** [comment]
ありがとうございます。1時間とまでいかなくとも、起動が遅いのは実感ありますね。
Bashのバージョンをいくつまでサポートするかは考えていましたが、一番気にしていたのはBSD系のオプションの違いなので、デフォルトのバージョンだけにしようと思います。

**Comment by jiro4989** [comment]
Mac環境にデフォルトで入っているawkだとテストがほぼ全滅ということがわかりました :thinking: 

gawkを入れるようにすればテストが通るようにもできるのですが、Mac環境をLinux環境に合わせに行くような形でテストをすることはMac環境でのテストと言えないと感じたので、諦めることにします :sweat: 

必要になったタイミング（無いと思うけれど）で再検討します。
