### ISSUE TITLE
カバレッジをとりたい

### ISSUE THREAD

**Issue by jiro4989** [unkontributors/super_unko#63]
Coverallsでカバレッジを可視化したい。
Bashのカバレッジをとるものだと[kcov](https://github.com/SimonKagstrom/kcov)か[shcov](https://github.com/SimonKagstrom/shcov)が候補。
ただしshcovはメンテされていないので、kcovの方を使うつもりです。
kcovはcoveralls対応らしいので。

**Comment by greymd** [comment]
![DS3zfv-VMAE8tIj](https://user-images.githubusercontent.com/3874767/67699710-77b7d580-f9a4-11e9-8572-42357181d86f.jpeg)

**Comment by jiro4989** [comment]
カバレッジ取れました
