### ISSUE TITLE
TravisCIからGitHub Actionsに移行したい

### ISSUE THREAD

**Issue by jiro4989** [unkontributors/super_unko#73]
@greymd 
TravisCIのVMの起動結構遅いなぁと感じてるのと
ワークフローの書きやすさと
GitHubとの親和性からCIサービスをGitHub Actionsに変更してみたいと考えてます。

移行までいかずとも、TravisCIとGitHub Actions両方平行稼働することも可能だと思います。
検証したいのですが、良いでしょうか？

**Comment by greymd** [comment]
@jiro4989  良いと思います！

**Comment by jiro4989** [comment]
#74 でdone
