### ISSUE TITLE
[投票締め切り] ロゴが欲しい

### ISSUE THREAD

**Issue by greymd** [unkontributors/super_unko#77]
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">＿人人人人人人人人人人人＿<br>＞　私もロゴが欲しい！　＜<br>￣Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^￣<br>　　　　　　👑<br>　　　　（💩💩💩）<br>　　　（💩👁💩👁💩）<br>　　（💩💩💩👃💩💩💩）<br>　（💩💩💩💩👄💩💩💩💩） <a href="https://t.co/stUpulbbut">https://t.co/stUpulbbut</a></p>&mdash; シェル芸bot (@minyoruminyon) <a href="https://twitter.com/minyoruminyon/status/1230432818074808320?ref_src=twsrc%5Etfw">February 20, 2020</a></blockquote>

**Comment by greymd** [comment]
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">super_unkoは世界でもっともクリーンなOSSなので、やはりロゴもクールで先進的でクリーンなロゴがふさわしいのでは・・・！？(´・ω・｀)</p>&mdash; Blacknon@お引越ししたい (@blacknon_) <a href="https://twitter.com/blacknon_/status/1221047316020203520?ref_src=twsrc%5Etfw">January 25, 2020</a></blockquote>

**Comment by greymd** [comment]
![EPI6-LKUEAM491h](https://user-images.githubusercontent.com/3874767/75099832-359f4900-55be-11ea-8472-72ba65525955.png)

<blockquote class="twitter-tweet"><p lang="und" dir="ltr"><a href="https://twitter.com/hashtag/super_unko%E3%83%AD%E3%82%B4%E6%A1%88?src=hash&amp;ref_src=twsrc%5Etfw">#super_unkoロゴ案</a><br> <a href="https://t.co/kKuKbhFTG2">https://t.co/kKuKbhFTG2</a> <a href="https://t.co/ZvfRvsiOvh">pic.twitter.com/ZvfRvsiOvh</a></p>&mdash; シェル芸bot (@minyoruminyon) <a href="https://twitter.com/minyoruminyon/status/1221103290332499968?ref_src=twsrc%5Etfw">January 25, 2020</a></blockquote>

**Comment by greymd** [comment]
![EPI6xVUU0AA8zoV](https://user-images.githubusercontent.com/3874767/75099837-4e0f6380-55be-11ea-9cad-07dbbb66786b.png)

<blockquote class="twitter-tweet"><p lang="und" dir="ltr"><a href="https://twitter.com/hashtag/super_unko%E3%83%AD%E3%82%B4%E6%A1%88?src=hash&amp;ref_src=twsrc%5Etfw">#super_unkoロゴ案</a><br> <a href="https://t.co/AzMHZ7O74O">https://t.co/AzMHZ7O74O</a> <a href="https://t.co/mQ5yR4Grf2">pic.twitter.com/mQ5yR4Grf2</a></p>&mdash; シェル芸bot (@minyoruminyon) <a href="https://twitter.com/minyoruminyon/status/1221103069527625729?ref_src=twsrc%5Etfw">January 25, 2020</a></blockquote>

**Comment by greymd** [comment]
![EPI2ldRUEAA7jlS](https://user-images.githubusercontent.com/3874767/75099849-6da68c00-55be-11ea-955f-8684d04a95fe.png)

<blockquote class="twitter-tweet"><p lang="und" dir="ltr"><a href="https://t.co/AvKEKbcjWn">https://t.co/AvKEKbcjWn</a> <a href="https://t.co/YpakEiryWl">pic.twitter.com/YpakEiryWl</a></p>&mdash; シェル芸bot (@minyoruminyon) <a href="https://twitter.com/minyoruminyon/status/1221098467591782401?ref_src=twsrc%5Etfw">January 25, 2020</a></blockquote>

**Comment by greymd** [comment]
<img width="517" alt="Screenshot 2020-02-22 at 21 59 38" src="https://user-images.githubusercontent.com/3874767/75099874-a3e40b80-55be-11ea-9ae2-0e3dd674287c.png">

<blockquote class="twitter-tweet"><p lang="und" dir="ltr"><a href="https://t.co/ZkPuIanf1K">https://t.co/ZkPuIanf1K</a> <a href="https://t.co/JUzGs726PK">pic.twitter.com/JUzGs726PK</a></p>&mdash; シェル芸bot (@minyoruminyon) <a href="https://twitter.com/minyoruminyon/status/1221073428762877952?ref_src=twsrc%5Etfw">January 25, 2020</a></blockquote>

**Comment by greymd** [comment]
![EPIbT-uVUAYF3Sj](https://user-images.githubusercontent.com/3874767/75099881-b6f6db80-55be-11ea-97e6-a0934f059bfe.png)

<blockquote class="twitter-tweet"><p lang="und" dir="ltr"><a href="https://t.co/r0VoCIDFqC">https://t.co/r0VoCIDFqC</a> <a href="https://t.co/biNkb3jNXR">pic.twitter.com/biNkb3jNXR</a></p>&mdash; シェル芸bot (@minyoruminyon) <a href="https://twitter.com/minyoruminyon/status/1221068481249959936?ref_src=twsrc%5Etfw">January 25, 2020</a></blockquote>

**Comment by greymd** [comment]
![EPIZRiYUcAAgoPj](https://user-images.githubusercontent.com/3874767/75099885-c9711500-55be-11ea-9ebf-af3598785f6a.png)

<blockquote class="twitter-tweet"><p lang="und" dir="ltr"><a href="https://t.co/HRQeur59Zd">https://t.co/HRQeur59Zd</a> <a href="https://t.co/cL5cOkHRcp">pic.twitter.com/cL5cOkHRcp</a></p>&mdash; シェル芸bot (@minyoruminyon) <a href="https://twitter.com/minyoruminyon/status/1221066239453216768?ref_src=twsrc%5Etfw">January 25, 2020</a></blockquote>

**Comment by greymd** [comment]
![EPIQ4CeU4AAVCxU](https://user-images.githubusercontent.com/3874767/75099896-ddb51200-55be-11ea-8caf-c997f619c722.png)

<blockquote class="twitter-tweet"><p lang="und" dir="ltr"><a href="https://t.co/eEmVWok9q2">https://t.co/eEmVWok9q2</a> <a href="https://t.co/S5tZUzHtd4">pic.twitter.com/S5tZUzHtd4</a></p>&mdash; シェル芸bot (@minyoruminyon) <a href="https://twitter.com/minyoruminyon/status/1221057005596528640?ref_src=twsrc%5Etfw">January 25, 2020</a></blockquote>

**Comment by greymd** [comment]
![EPINi8lUwAAk19J](https://user-images.githubusercontent.com/3874767/75099903-f291a580-55be-11ea-892f-4afa79ff6a25.png)

<blockquote class="twitter-tweet"><p lang="und" dir="ltr"><a href="https://t.co/8yo9Z9HTCN">https://t.co/8yo9Z9HTCN</a> <a href="https://t.co/TqoKrRmx2Q">pic.twitter.com/TqoKrRmx2Q</a></p>&mdash; シェル芸bot (@minyoruminyon) <a href="https://twitter.com/minyoruminyon/status/1221053344581468160?ref_src=twsrc%5Etfw">January 25, 2020</a></blockquote>

**Comment by greymd** [comment]
![EPILGzxUYAAKyo1](https://user-images.githubusercontent.com/3874767/75099908-01785800-55bf-11ea-8779-d6abc77ec01f.png)
<blockquote class="twitter-tweet"><p lang="und" dir="ltr"><a href="https://t.co/QN7bHBh41r">https://t.co/QN7bHBh41r</a> <a href="https://t.co/5J1pik6Rcx">pic.twitter.com/5J1pik6Rcx</a></p>&mdash; シェル芸bot (@minyoruminyon) <a href="https://twitter.com/minyoruminyon/status/1221050662080790528?ref_src=twsrc%5Etfw">January 25, 2020</a></blockquote>

**Comment by greymd** [comment]
![EPIGIOjUEAA9gpP](https://user-images.githubusercontent.com/3874767/75099913-19e87280-55bf-11ea-84fc-b6c22c68664b.png)
<blockquote class="twitter-tweet"><p lang="und" dir="ltr"><a href="https://twitter.com/hashtag/super_unko%E3%83%AD%E3%82%B4%E6%A1%88?src=hash&amp;ref_src=twsrc%5Etfw">#super_unkoロゴ案</a><br> <a href="https://t.co/uSEtV5BC0b">https://t.co/uSEtV5BC0b</a> <a href="https://t.co/mLwlKZwfEz">pic.twitter.com/mLwlKZwfEz</a></p>&mdash; シェル芸bot (@minyoruminyon) <a href="https://twitter.com/minyoruminyon/status/1221045188971253761?ref_src=twsrc%5Etfw">January 25, 2020</a></blockquote>

**Comment by greymd** [comment]
![EPID5Q0UUAAAmG_](https://user-images.githubusercontent.com/3874767/75099920-2bca1580-55bf-11ea-9a3b-d6f872c5af9b.png)

<blockquote class="twitter-tweet"><p lang="und" dir="ltr"><a href="https://twitter.com/hashtag/super_unko%E3%83%AD%E3%82%B4%E6%A1%88%E6%94%B9?src=hash&amp;ref_src=twsrc%5Etfw">#super_unkoロゴ案改</a><br> <a href="https://t.co/i5qe3puR1c">https://t.co/i5qe3puR1c</a> <a href="https://t.co/IhyyKAfTXm">pic.twitter.com/IhyyKAfTXm</a></p>&mdash; シェル芸bot (@minyoruminyon) <a href="https://twitter.com/minyoruminyon/status/1221042732648423424?ref_src=twsrc%5Etfw">January 25, 2020</a></blockquote>

**Comment by greymd** [comment]
![EPIBl93VAAIYjQU](https://user-images.githubusercontent.com/3874767/75099929-400e1280-55bf-11ea-8fd0-1b1911b3d1e8.png)

<blockquote class="twitter-tweet"><p lang="und" dir="ltr"><a href="https://twitter.com/hashtag/super_unko%E3%83%AD%E3%82%B4%E6%A1%88?src=hash&amp;ref_src=twsrc%5Etfw">#super_unkoロゴ案</a><br> <a href="https://t.co/Ti07Uo4dcM">https://t.co/Ti07Uo4dcM</a> <a href="https://t.co/g8x5jmwQIW">pic.twitter.com/g8x5jmwQIW</a></p>&mdash; シェル芸bot (@minyoruminyon) <a href="https://twitter.com/minyoruminyon/status/1221040202107326466?ref_src=twsrc%5Etfw">January 25, 2020</a></blockquote>

**Comment by greymd** [comment]
## どれにするか？
Issue に貼り付けてたくさん 👍 をもらったやつにする？

## ライセンス
ソフトウェアは💩ライセンス（BSDみたいなやつ）なので、ロゴは「クリエイティブ💩ライセンス」を定義します。
このライセンスのもとでは、あらゆる作品は💩になるので、再配布や改変、商用利用がOKになります。
つまりただのパブリックドメインです（著作権を放棄することになるので、それに同意いただける方の作った作品にします）。

パブリックドメインにして、suzuriとかで売上金0円に設定してマグカップ作って味噌汁飲みましょう。

**Comment by mikkun** [comment]
クリーンなロゴを作ってみました。
ロゴ案に混ぜて頂ければ幸いです:hankey:
![super_unko](https://user-images.githubusercontent.com/3395192/75274225-d3587980-5845-11ea-8b37-e3a35311a5fa.png)

**Comment by greymd** [comment]
なんとなく https://hatchful.shopify.com/ で作ってみた

![pinterest_profile_image](https://user-images.githubusercontent.com/3874767/75298666-05a8ad80-582b-11ea-9993-7e8dfe2a4aa0.png)

**Comment by t-koba** [comment]
あんまりクリーンじゃない気がする…

![super_unko_1](https://user-images.githubusercontent.com/7821157/76154398-19072300-611f-11ea-89dd-9974320ac81c.png)

**Comment by t-koba** [comment]
![super_unko_2](https://user-images.githubusercontent.com/7821157/76154421-5370c000-611f-11ea-97d3-d213b6d78e19.png)

**Comment by greymd** [comment]
締め切りました
👍の数集計

https://github.com/unkontributors/super_unko/issues/77#issuecomment-590002148
=> 4

https://github.com/unkontributors/super_unko/issues/77#issuecomment-590002462
=> 5

https://github.com/unkontributors/super_unko/issues/77#issuecomment-591001085
=> 4

https://github.com/unkontributors/super_unko/issues/77#issuecomment-591150259
=> 4

https://github.com/unkontributors/super_unko/issues/77#issuecomment-596152151
=> 6

**Comment by greymd** [comment]
@t-koba さん、おめでとうございます！
あなたのロゴが選ばれました！！

一応確認ですが下記に同意いただける旨大丈夫ですかね？？

> ソフトウェアは💩ライセンス（BSDみたいなやつ）なので、ロゴは「クリエイティブ💩ライセンス」（クリエイティブ・ウンコモンライセンス）を定義しようと思います。
このライセンスのもとでは、あらゆる作品は💩になるので、再配布や改変、商用利用がOKになります。
つまりただのパブリックドメインです（著作権を放棄することになるので、それに同意いただける方の作った作品にします）。

**Comment by t-koba** [comment]
やったー！「クリエイティブ💩ライセンス」でお願いします！！

**Comment by greymd** [comment]
merged #83
