### ISSUE TITLE
Change the default branch from "master" to something else

### ISSUE THREAD

**Issue by greymd** [unkontributors/super_unko#86]
First of all, super_unko is an OSS based on poop(unko).
I still think the default branch name should be "anus" to remind us of the scene where the poop is released from anus when the version is upgraded.
How do you think about it?

super_unko はウンコをテーマとしたOSSなので、バージョンアップ時には肛門からウンコが放出される場面を彷彿とさせるために、デフォルトのブランチ名は "anus" が良いのではないかと思うわけです。

**Comment by xztaityozx** [comment]
デフォルトブランチ名を変えることには賛成です。ただし"anus"よりは"oshiri"が良いと考えます

理由としては
- ウンコと同じ日本語
- (同じ日本語でなら)肛門よりは親しみやすい
- なんだかかわいい
などが挙げられます

**Comment by jiro4989** [comment]
"oshiri" が候補になるのでしたら、"ketsu" も候補に加えていただきたく。
"ketsu" は "oshiri" より力強さという点で勝る響きがあると思っています。

**Comment by greymd** [comment]
（メモ）CIまわりで変更が必要そう

```bash
$ git grep master
PULL_REQUEST_TEMPLATE.md:  * (Case: failing `test`) Please run tests and fix your code (see also: [Testing](https://github.com/unkontributors/super_unko/blob/master/README.md#testing))
PULL_REQUEST_TEMPLATE.md:  * (Case: failing `format`) Please run `./linter.sh format-save` (see also: [CodeStyle and lint](https://github.com/unkontributors/super_unko/blob/master/README.md#codestyle-and-lint))
PULL_REQUEST_TEMPLATE.md:  * (Case: failing `lint`) Please run linter and fix your code (see also: [CodeStyle and lint](https://github.com/unkontributors/super_unko/blob/master/README.md#codestyle-and-lint))
workflows/unko.yml:    if: github.ref == 'refs/heads/master'
workflows/unko.yml:          wget https://raw.githubusercontent.com/ekalinin/github-markdown-toc/master/gh-md-toc
```

**Comment by greymd** [comment]
やや、頭が硬かった。たしかに、日本語にあわせるのは賛成です。
そもそもなのですが、世の中の解き放たれるという意味では "benki" もありなのではないかと思えてきました。
しかしウンコにとって benki とは役目を終えて行く墓場、という印象もあるのでちょっと微妙？

**Comment by jiro4989** [comment]
便器を通過し、下水を通り、土や肥料となって人間にまた反ってくると考えれば、
"benki"から「再生」を感じられるとも思いました。

**Comment by greymd** [comment]
```
$ git push origin oshiri
$ git push origin ketsu
$ git push origin benki
```

この中からだと、今の所oshiriがしっくり来るんですよね。理由はわからないんですが。
origin と oshiri が韻を踏んでる感じがあるからですかね？

**Comment by xztaityozx** [comment]
自分で提案しておいてですが、oshiriにウンコをpushするというのは、少し不健康にも感じます。

しかし我々が「おしりの内側から広い世界へウンコをpushする」と考えると良く感じます。同等にbenkiも良い案だと思います

**Comment by ryuichiueda** [comment]
oshiriにunkoをpushするのは、弾を込める感じがして自分は好きです。


とても好きです。

**Comment by jiro4989** [comment]
oshiriにunkoをpushしつづけるだけでは具合が悪くなる懸念があります。
開発のフローを整備し、定期的にreleaseすることをREADMEに明記する必要もありそうですね

**Comment by jiro4989** [comment]
push以外の操作についてはどうでしょうか？
benkiをpullする、benkiをforkする、など

**Comment by greymd** [comment]
```
$ git pull origin oshiri
$ git pull origin ketsu
$ git pull origin benki
```

benkiに水を引いてくる感がある

**Comment by jiro4989** [comment]
git pull origin ketsu はプルケツと発音できてしまい、また違った印象を抱いてしまいそうですね...

**Comment by kunst1080** [comment]
私は oshiri ブランチに一票を投じます。

> oshiriにウンコをpushするというのは、少し不健康にも感じます。

この件ですが、一般的に、現 master ブランチへの直接 push は作法としてもよろしくないものであると思います。そのため、「oshiriにウンコをpushするというのは、少し不健康」というのは正しい認識であると思います。

むしろ、 oshiri ブランチへの直接 push を防ぐことができるため効果的ではないでしょうか。

**Comment by greymd** [comment]
なるほど、確かに。直接のpushは基本的にイレギュラーという認識が周知できる、むしろ優れた命名かもしれませんね。
では、oshiriでいきますかね。

**Comment by jiro4989** [comment]
なるほど。きちんとGitHubの機能を使って、oshiriを保護するということですね

**Comment by blacknon** [comment]
> git pull origin ketsu はプルケツと発音できてしまい、また違った印象を抱いてしまいそうですね...


この理屈だと、`git pull origin chin`はプルチンと発音できますね。

**Comment by greymd** [comment]
変えます
![Screenshot 2020-06-12 at 12 57 41](https://user-images.githubusercontent.com/3874767/84500413-665dd800-acac-11ea-853e-4641c9c084e4.png)

**Comment by greymd** [comment]
`master`から`oshiri`への移行ですが、意外とスムーズに完了し、CI周りも一応問題なさそうです。
https://github.com/unkontributors/super_unko/runs/765348199

しかしながら、なにか不備に気づいた方は別途トピックブランチを切ってプルリクエストをお願いします。なお、周知の通りと思いますが、**プルリクエストの送り先は`master`ではありません、`oshiri`です。`oshiri`にプルリクエストを投げてください。**
それでは、本 Issue はクローズします。議論にお付き合いいただきありがとうございました。

**Comment by fumiyas** [comment]
```console
$ git remote rename origin unko
```

しておくとよくわかんなくなりそう。

**Comment by papiron** [comment]
ブランチ名って絵文字ダメなんですかね💩
