### ISSUE TITLE
README.md内 ｢うんこ｣の訳を｢shit｣から｢poop｣にしたい

### ISSUE THREAD

**Issue by ghost** [unkontributors/super_unko#88]
｢うんこ｣ の訳として ｢shit｣ はかわいくないので ｢poop｣ にしたいです.
理由として, [poop](https://en.wiktionary.org/wiki/poop) は直接的な ｢うんこ｣ という意味を持つ一方で, [shit](https://en.wiktionary.org/wiki/shit#English) は強い感情がこもった使われ方 (もちろん排便することも示します) や, 役に立たないものという意味を持つことが挙げられます.

上記の基準をもとにREADME.mdの ｢shit｣ をshit のままにするか ｢poop｣ にするか検討しました.

---
https://github.com/unkontributors/super_unko/blob/c8158ad425f39868fcf9664c85f42a5d5f186130/README.md#L11
｢役に立たない｣ を意味するので ｢shit｣ (文法上はshitty)
https://github.com/unkontributors/super_unko/blob/c8158ad425f39868fcf9664c85f42a5d5f186130/README.md#L56-L61
｢うんこ｣ を意味するのですべて ｢poop｣

---
以上, 感想をいただけるとありがたいです.

**Comment by greymd** [comment]
確かにpoopのほうが日本語の「うんこ」にニュアンスが近くて、良いと思います！
shitの個所は、本リポジトリができた直後になし崩し的に記述した記憶があるので、スタンスが定まってなかったかもしれないですねー。。

**Comment by ghost** [comment]
あーそうなんですか. ありがとうございます!

**Comment by greymd** [comment]
更新done #89
