### ISSUE TITLE
update-repositoryがコケる

### ISSUE THREAD

**Issue by jiro4989** [unkontributors/super_unko#92]
https://github.com/unkontributors/super_unko/runs/1032766332?check_suite_focus=true

**Comment by greymd** [comment]
https://github.com/unkontributors/super_unko/runs/1032766332?check_suite_focus=true
```
 Print .tar2package.yml0s
libdir : /usr/lib
Run cat .tar2package.yml
name : superunko
cmdname : superunko
summary : Super Unko
description : super_unko project is the one of the awesome, clean and sophisticated OSS project in the world. Let us create shit commands.
version : 
changelog : unko.tower power up
url : https://github.com/unkontributors/super_unko
author : Awesome Unkontributors
email : super@unko.com
libdir : /usr/lib
```

...

```
dpkg-buildpackage: error: version number does not start with digit
```


version が空でコケている。。？

**Comment by jiro4989** [comment]
```bash
  echo ::set-output name=tag::$(git tag -l '*.*.*' | sort -V | tail -n 1)
```

の結果が空になってるみたいですね

**Comment by jiro4989** [comment]
`git tag -l` の結果が空。 checkout アクションを v2 に上げたのが原因か

**Comment by jiro4989** [comment]
https://github.com/actions/checkout

> Only a single commit is fetched by default, for the ref/SHA that triggered the workflow. Set fetch-depth: 0 to fetch all history for all branches and tags. Refer here to learn which commit $GITHUB_SHA points to for different events.

デフォルトで最新のコミットだけ落としてくるのかな。 git clone --depth 1 するようにしたのかな

**Comment by jiro4989** [comment]
> Set fetch-depth: 0 to fetch all history for all branches and tags.

`fetch-depth: 0` が必要と

**Comment by greymd** [comment]
はい。
#94 でマージしてしまいました。

**Comment by jiro4989** [comment]
ありがとうございます。 release.yml にも fetch-depth が必要だったので追加しました
